<a href="https://colab.research.google.com/github/AM0ya/Clase_Programacion/blob/main/S06_Actividad_02_ALGEBRALINEAL_269712.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [30]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [31]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [32]:
# Tu código aquí

# Calculamos la norma (magnitud) de cada vector con np.linalg.norm()
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

# Imprimimos los resultados
print(f"Norma Producto A: {norma_A:.4f}")
print(f"Norma Producto B: {norma_B:.4f}")
print(f"Norma Producto C: {norma_C:.4f}")



Norma Producto A: 7.4492
Norma Producto B: 6.7772
Norma Producto C: 5.2383


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [33]:
# Tu código aquí


# 1. Producto punto usando np.dot() o @
dot_AB = np.dot(producto_A, producto_B)
dot_AC = np.dot(producto_A, producto_C)

# 2. Coseno del ángulo y conversión a grados con np.arccos() y np.degrees()
cos_AB = dot_AB / (norma_A * norma_B)
angulo_AB_deg = np.degrees(np.arccos(cos_AB))

cos_AC = dot_AC / (norma_A * norma_C)
angulo_AC_deg = np.degrees(np.arccos(cos_AC))

print(f"Producto punto A y B: {dot_AB:.4f} | Ángulo: {angulo_AB_deg:.2f}°")
print(f"Producto punto A y C: {dot_AC:.4f} | Ángulo: {angulo_AC_deg:.2f}°")


Producto punto A y B: 50.4600 | Ángulo: 1.77°
Producto punto A y C: 26.5000 | Ángulo: 47.23°


El Producto B es más similar al Producto A, ya que el ángulo entre sus vectores es de tan solo 3.03°, en comparación con los 65.54° entre A y C.
El ángulo es el indicador correcto porque mide la orientación relativa de los vectores en el espacio (la proporción relativa entre calidad, precio y servicio), ignorando la magnitud o escala absoluta del vector. Dos productos con proporciones similares de atributos apuntarán en una dirección casi identica.

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [34]:
# Tu código aquí

# Obtenemos los vectores unitarios dividiendo cada vector entre su propia norma
unitario_A = producto_A / norma_A
unitario_B = producto_B / norma_B
unitario_C = producto_C / norma_C

# Verificamos e imprimimos que la norma de cada vector unitario sea exactamente 1.0
print("Unitario A:", np.round(unitario_A, 4), "| Norma:", np.linalg.norm(unitario_A))
print("Unitario B:", np.round(unitario_B, 4), "| Norma:", np.linalg.norm(unitario_B))
print("Unitario C:", np.round(unitario_C, 4), "| Norma:", np.linalg.norm(unitario_C))



Unitario A: [0.6041 0.4296 0.6712] | Norma: 1.0
Unitario B: [0.5902 0.4132 0.6935] | Norma: 1.0
Unitario C: [0.1909 0.9545 0.2291] | Norma: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [35]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [36]:
# Tu código aquí

# 1. Multiplicación elemento a elemento (*) vs Multiplicación matricial (@)
mult_elem = M * P
mult_mat = M @ P

# 2. Comprobación de compatibilidad y conmutatividad P @ M
mult_mat_PM = P @ M

print("M * P (elemento a elemento):\n", mult_elem)
print("\nM @ P (multiplicación matricial):\n", mult_mat)
print("\nP @ M (orden inverso):\n", mult_mat_PM)


M * P (elemento a elemento):
 [[3. 0.]
 [0. 6.]]

M @ P (multiplicación matricial):
 [[3.  2. ]
 [1.5 6. ]]

P @ M (orden inverso):
 [[3.  1.5]
 [2.  6. ]]


Respuestas:
1. ⁠M * P⁠ realiza una multiplicación término a término $(m_{ij} \times p_{ij})$, mientras que ⁠M @ P⁠ ejecuta el producto punto entre cada fila de ⁠M⁠ y cada columna de ⁠P⁠ siguiendo las reglas del álgebra lineal.
2. ⁠P @ M⁠ es compatible porque ambas son matrices de $2 \times 2$. Sin embargo, no da el mismo resultado que ⁠M @ P⁠, demostrando que la multiplicación matricial no es conmutativa $(M \cdot P \neq P \cdot M)$."

---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [37]:
# Tu código aquí

# 1. Determinante de M con np.linalg.det()
det_M = np.linalg.det(M)
print(f"Determinante de M: {det_M:.4f}")

# 2. Inversa de M con np.linalg.inv()
M_inv = np.linalg.inv(M)
print("\nMatriz Inversa (M_inv):\n", M_inv)

# 3. Verificación M @ M_inv (debe aproximarse a la matriz identidad)
identidad_verif = M @ M_inv

print("\nVerificación (M @ M_inv):\n", np.round(identidad_verif, 4))



Determinante de M: 5.0000

Matriz Inversa (M_inv):
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Verificación (M @ M_inv):
 [[ 1.  0.]
 [-0.  1.]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [38]:
b = np.array([180, 300])

# Tu código aquí


# 1. Resolver Mx = b con np.linalg.solve()
x = np.linalg.solve(M, b)

# 2. Verificación M @ x == b
verificacion_b = M @ x

print("Solución x (Unidades necesarias de cada insumo):", x)
print("Verificación M @ x:", verificacion_b)


Solución x (Unidades necesarias de cada insumo): [48. 84.]
Verificación M @ x: [180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [39]:
# Tu código aquí

# 1. Distancia euclidiana usando la norma de la diferencia: np.linalg.norm(a - b)
dist_AB = np.linalg.norm(producto_A - producto_B)
dist_AC = np.linalg.norm(producto_A - producto_C)

# 2. Similitud coseno: (a . b) / (||a|| * ||b||)
sim_cos_AB = np.dot(producto_A, producto_B) / (norma_A * norma_B)
sim_cos_AC = np.dot(producto_A, producto_C) / (norma_A * norma_C)

# 3. Conclusión en cadena de texto impresa
resumen_conclusion = f"""
=== EVALUACIÓN DE SIMILITUD ENTRE PRODUCTOS ===

1. Distancia Euclidiana:
   - Distancia (A, B): {dist_AB:.4f}
   - Distancia (A, C): {dist_AC:.4f}

2. Similitud Coseno:
   - Similitud Coseno (A, B): {sim_cos_AB:.4f}
   - Similitud Coseno (A, C): {sim_cos_AC:.4f}

CONCLUSIÓN FINAL:
El Producto B es significativamente más parecido al Producto A que el Producto C.
Ambas métricas coinciden plenamente en esta conclusión:
- El Producto B presenta una menor distancia euclidiana ({dist_AB:.4f} < {dist_AC:.4f}).
- El Producto B presenta una mayor similitud coseno ({sim_cos_AB:.4f} > {sim_cos_AC:.4f}).
"""

print(resumen_conclusion)



=== EVALUACIÓN DE SIMILITUD ENTRE PRODUCTOS ===

1. Distancia Euclidiana:
   - Distancia (A, B): 0.7071
   - Distancia (A, C): 5.4708

2. Similitud Coseno:
   - Similitud Coseno (A, B): 0.9995
   - Similitud Coseno (A, C): 0.6791

CONCLUSIÓN FINAL:
El Producto B es significativamente más parecido al Producto A que el Producto C.
Ambas métricas coinciden plenamente en esta conclusión:
- El Producto B presenta una menor distancia euclidiana (0.7071 < 5.4708).
- El Producto B presenta una mayor similitud coseno (0.9995 > 0.6791).



---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.